[project]
name = "jabs-vision"
version = "0.3.0"
description = ""
readme = "README.md"
requires-python = ">=3.10,<3.15"
license = { text = "Proprietary" }

authors = [
  { name = "Glen Beane" },
  { name = "Alexander Berger-Liedtka" },
  { name = "Keith Sheppard" },
]

dependencies = [
    "jabs-io",
    "jabs-core",
    "hydra-core>=1.3.2",
    "torch>=2.9.1",
    "torchvision>=0.24.1",
]

[tool.uv.sources]
jabs-io = { workspace = true }
jabs-core = { workspace = true }

[project.optional-dependencies]
plot = [
    "matplotlib>=3.10.8",
]
mlflow = [
    "mlflow>=3.8.1",
]
wandb = [
    "wandb>=0.24.0",
]
submitit = [
    "submitit>=1.5.4",
]
timm = [
    "timm>=1.0.0",
]
hrnet_leoxiaobin = [
    "yacs>=0.1.8",
]

[dependency-groups]
dev = [
  {include-group = "lint"},
  {include-group = "test"},
  "pre-commit>=4.2.0,<5.0.0",
  "matplotlib>=3.9.3,<4.0.0",
]
test = [
  "pytest>=8.3.4,<9.0.0",
  "pytest-cov>=7.0.0",
]
lint = [
  "ruff>=0.11.5,<0.12.0",
]

[project.urls]
Repository = "https://github.com/KumarLabJax/JABS-behavior-classifier"
Issues = "https://github.com/KumarLabJax/JABS-behavior-classifier/issues"

[build-system]
requires = ["uv_build>=0.9.26,<0.10.0"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-name = "jabs.vision"
