[project]
name = "jabs-core"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10,<3.15"
dependencies = [
  "packaging>=24.0",
  "toml>=0.10.2,<0.11.0",
  "h5py>=3.10.0,<4.0.0",
  "shapely>=2.0.1,<3.0.0",
  "numpy>=2.0.0,<3.0.0",
  "opencv-python-headless>=4.8.1.78,<5.0.0",
]

[dependency-groups]
dev = [
  {include-group = "lint"},
  {include-group = "test"},
  {include-group = "docs"},
  "pre-commit>=4.2.0,<5.0.0",
  "matplotlib>=3.9.3,<4.0.0",
]
test = [
  "pytest>=8.3.4,<9.0.0",
  "pytest-cov>=7.0.0",
]
lint = [
  "ruff>=0.11.5,<0.12.0",
]
docs = [
  "mkdocs>=1.6.1",
]

[project.urls]
Repository = "https://github.com/KumarLabJax/JABS-behavior-classifier"
Issues = "https://github.com/KumarLabJax/JABS-behavior-classifier/issues"

[build-system]
requires = ["uv_build>=0.9.26,<0.10.0"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-name = "jabs.core"
