[project]
name = "jabs-io"
version = "0.41.0a5"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10,<3.15"
license = { text = "Proprietary" }

authors = [
  { name = "Glen Beane" },
  { name = "Alexander Berger-Liedtka" },
  { name = "Keith Sheppard" },
]

dependencies = [
    "jabs-core",
    "numpy>=2.0.0,<3.0.0",
]

[tool.uv.sources]
jabs-core = { workspace = true }

[dependency-groups]
dev = [
  {include-group = "lint"},
  {include-group = "test"},
  {include-group = "docs"},
  "pre-commit>=4.2.0,<5.0.0",
  "matplotlib>=3.9.3,<4.0.0",
]
test = [
  "pytest>=8.3.4,<9.0.0",
  "pytest-cov>=7.0.0",
]
lint = [
  "ruff>=0.11.5,<0.12.0",
]
docs = [
  "mkdocs>=1.6.1",
]

[project.urls]
Repository = "https://github.com/KumarLabJax/JABS-behavior-classifier"
Issues = "https://github.com/KumarLabJax/JABS-behavior-classifier/issues"

[project.optional-dependencies]
nwb = [
    "ndx-pose>=0.2.2",
    "pynwb>=3.1.3",
]
h5py = [
    "h5py>=3.15.1",
]
parquet = [
    "pyarrow>=18.0.0",
]

[build-system]
requires = ["uv_build>=0.9.26,<0.10.0"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-name = "jabs.io"
